# Generated by Django 3.0.1 on 2020-02-23 20:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('url', models.URLField(validators=[django.core.validators.RegexValidator('^(https?\\:\\/\\/)?(www\\.youtube\\.com|youtu\\.?be)\\/.+$', 'Only youtube url')])),
                ('file_path', models.FilePathField(null=True)),
                ('download_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
