# Generated by Django 3.0.3 on 2020-02-24 08:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubemodel',
            name='download_url',
        ),
        migrations.RemoveField(
            model_name='youtubemodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='youtubemodel',
            name='file_path',
        ),
        migrations.AddField(
            model_name='youtubemodel',
            name='mp3_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='youtubemodel',
            name='mp3_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='youtubemodel',
            name='url',
            field=models.URLField(),
        ),
    ]
